title: Carlos Aguni Personal Blog
description: ~~Tales of an eternal apprentice~~
author: Carlos Aguni
github: https://github.com/crashlaker
about: Highly motivated self-taught IT analyst. Always learning and ready to explore new skills. An eternal apprentice.
google_analytics: 


owner:
  disqus-shortname: crashlaker

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    #- icon: fa-twitter
    #  link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/carlos-aguni"
    #- icon: fa-stack-exchange
    #  link: "#"
    - icon: fa-github
      link: "https://github.com/crashlaker"

share:
  twitter_username: github.io
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: Tags
      url: /tags
    - text: My Projects
      url: /projects/
    #- text: XML Feed
    #  url: /feed.xml

url: "https://crashlaker.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
#markdown: CommonMarkGhPages
markdown: kramdown
#kramdown:
#    parse_block_html: true
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  parse_block_html: true
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
gems:
  - jekyll-paginate
  - jekyll-gist

#compress_html:
#  clippings: all
#  comments: ["<!-- ", " -->"]
#  endings: all
#  ignore:
#    envs: ['development']
